matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

        
language: c++

dist: trusty
sudo: required
group: edge
warnings_are_errors: false

env:
  global:
    - POCL_LLVM_VERSION=5.0
    - POCL_LLVM_CONFIG=/usr/lib/llvm-${POCL_LLVM_VERSION}/bin/llvm-config
    - POCL_CXX_COMPILER=/usr/lib/llvm-${POCL_LLVM_VERSION}/bin/clang++
    - POCL_C_COMPILER=/usr/lib/llvm-${POCL_LLVM_VERSION}/bin/clang

compiler:
  - g++
  
before_install:
  - HOMEDIR="$PWD"
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq -y
  - sudo apt-get install -qq -y --force-yes opencl-headers g++-4.8 cmake git libtool libhwloc-dev wget g++ pkg-config libpthread-stubs0-dev clang-5.0 lldb-5.0 libclang-5.0-dev
  - export CXX="g++-4.8"
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - git clone https://github.com/viennacl/viennacl-dev.git
  
install:
  - |
    cd ..
    git clone -b release_1_0 https://github.com/pocl/pocl.git pocl
    cd pocl
    mkdir build
    cd build
    cmake -DWITH_LLVM_CONFIG=${POCL_LLVM_CONFIG} -DCMAKE_INSTALL_PREFIX=/usr ..
    make
    sudo make install
  - cd $HOMEDIR
  - sudo ldconfig
  
  
script:
  - cd viennacl-dev/examples/tutorial
  - g++ -o viennacl-info viennacl-info.cpp -lOpenCL -I../..
  - ./viennacl-info

notifications:
  email:
    on_success: change
    on_failure: change
